import {
  User,
  Temple,
  PriestProfile,
  Vacancy,
  Application,
  Message,
  ContributorProposal,
  TempleClaimRequest,
  AppNotification,
  AuditLog,
} from '../src/types';
import { initialTemples } from './templesData';

export interface DatabaseState {
  users: User[];
  temples: Temple[];
  priestProfiles: PriestProfile[];
  vacancies: Vacancy[];
  applications: Application[];
  messages: Message[];
  contributorProposals: ContributorProposal[];
  claimRequests: TempleClaimRequest[];
  notifications: AppNotification[];
  auditLogs: AuditLog[];
}

export const db: DatabaseState = {
  users: [
    {
      id: 'user-devotee-1',
      email: 'devotee@templeconnect.org',
      role: 'user',
      name: 'Ramesh Kumar',
      phone: '+91 98410 12345',
      createdAt: '2025-01-10T10:00:00Z',
    },
    {
      id: 'user-admin-meenakshi',
      email: 'admin@meenakshi.org',
      role: 'admin',
      name: 'Sundaram Gurukkal (Trustee)',
      phone: '+91 94432 98765',
      templeId: 'temple-meenakshi',
      createdAt: '2024-11-01T08:30:00Z',
    },
    {
      id: 'user-admin-somnath',
      email: 'admin@somnath.org',
      role: 'admin',
      name: 'Dharmendra Shastri (Board)',
      phone: '+91 98250 45678',
      templeId: 'temple-somnath',
      createdAt: '2024-12-15T09:00:00Z',
    },
    {
      id: 'user-priest-sharma',
      email: 'priest.sharma@vedic.org',
      role: 'priest',
      name: 'Pandit Rajesh Sharma',
      phone: '+91 98765 43210',
      priestProfileId: 'priest-sharma-profile',
      createdAt: '2024-12-20T11:00:00Z',
    },
    {
      id: 'user-priest-venkat',
      email: 'priest.venkat@vedic.org',
      role: 'priest',
      name: 'Shri Venkatachari Swami',
      phone: '+91 98450 67890',
      priestProfileId: 'priest-venkat-profile',
      createdAt: '2025-01-05T14:20:00Z',
    },
  ],

  temples: [...initialTemples],

  priestProfiles: [
    {
      id: 'priest-sharma-profile',
      userId: 'user-priest-sharma',
      fullName: 'Pandit Rajesh Sharma',
      experienceYears: 12,
      previousTemples: [
        {
          templeName: 'Kashi Vishwanath Sub-Shrine',
          role: 'Assistant Acharya (Rudrabhishekam & Archana)',
          duration: '2016 – 2021',
          city: 'Varanasi',
        },
        {
          templeName: 'Sri Raghavendra Swamy Mutt',
          role: 'Purohit & Veda Parayana Adhyapaka',
          duration: '2021 – 2024',
          city: 'Madurai',
        },
      ],
      purohithamSkills: [
        'Rudrabhishekam',
        'Ganapathi Homam',
        'Navagraha Shanthi',
        'Veda Parayanam',
        'Vivaham / Wedding Rites',
        'Satyanarayana Vratam',
        'Maha Sudarshana Homam',
      ],
      vedaTradition: 'Rigveda - Shakala Shakha',
      trainingQualifications: 'Sri Venkateswara Veda Pathashala - Kramanta Completed (8-Year Rigveda Adhyayanam)',
      languages: ['Sanskrit', 'Hindi', 'Tamil', 'Telugu'],
      achievements: 'Veda Vibhushan Title awarded by Jagadguru Shankaracharya Peetham (2022). Performed over 250 Shatachandi and Rudra Homams.',
      bio: 'Disciplined Rigvedic Purohit dedicated to authentic Agamic traditions, precise svara chanting, and devout deity alankaram. Seeking long-term service in a consecrated Shiva or Devi temple.',
      location: 'Madurai, Tamil Nadu (Willing to relocate across India)',
      phone: '+91 98765 43210',
      email: 'priest.sharma@vedic.org',
      shareContactConsent: true,
      availableForRelocation: true,
      expectedRemuneration: '₹40,000 – ₹55,000 / month + Traditional Temple Accommodation',
      verifiedAgama: true,
    },
    {
      id: 'priest-venkat-profile',
      userId: 'user-priest-venkat',
      fullName: 'Shri Venkatachari Swami',
      experienceYears: 16,
      previousTemples: [
        {
          templeName: 'Sri Varadaraja Perumal Temple',
          role: 'Pancharatra Agama Archakar',
          duration: '2012 – 2023',
          city: 'Kanchipuram',
        },
      ],
      purohithamSkills: [
        'Pancharatra Agama Seva',
        'Alankaram & Pushpa Kainkaryam',
        'Kalyana Utsavam',
        'Sudarshana Homam',
        'Veda Parayanam',
        'Brahmotsavam Vahana Nirvahana',
      ],
      vedaTradition: 'Krishna Yajurveda - Taittiriya Shakha',
      trainingQualifications: 'Madurantakam Veda Agama Pathashala (Pancharatra Agama Praveena)',
      languages: ['Tamil', 'Telugu', 'Sanskrit', 'English'],
      achievements: 'Agama Ratnakara recipient; specialized in rare flower alankarams and Utsava Vigraha procession protocol.',
      bio: 'Experienced Pancharatra Archakar with 16 years of continuous sanctum service in Vaishnavite kshetras. Highly skilled in daily pujas, nitya tirumanjanam, and annual Brahmotsavam management.',
      location: 'Chennai / Kanchipuram, Tamil Nadu',
      phone: '+91 98450 67890',
      email: 'priest.venkat@vedic.org',
      shareContactConsent: true,
      availableForRelocation: true,
      expectedRemuneration: '₹45,000 – ₹60,000 / month',
      verifiedAgama: true,
    },
  ],

  vacancies: [
    {
      id: 'vac-somnath-1',
      templeId: 'temple-somnath',
      templeName: 'Shree Somnath Jyotirlinga Temple',
      location: 'Prabhas Patan, Gujarat',
      title: 'Senior Vedic Archaka & Rudrabhishekam Specialist',
      ritualSpecialization: [
        'Rudrabhishekam',
        'Veda Parayanam',
        'Laghu Rudra / Maha Rudra',
        'Daily Sanctum Arati',
      ],
      vedaTraditionRequired: 'Rigveda or Shukla Yajurveda',
      minExperienceYears: 7,
      remuneration: '₹45,000 – ₹60,000 / month + Free Temple Quarters + Prasadam',
      accommodationProvided: true,
      foodProvided: true,
      description: 'Shree Somnath Trust invites applications from certified Vedic Purohits to conduct early-morning Laghu Rudra abhishekams, daily deeparadhana, and lead Veda Parayanam at the sanctum sanctorum.',
      status: 'open',
      postedDate: '2025-01-15',
      applicantsCount: 2,
    },
    {
      id: 'vac-meenakshi-1',
      templeId: 'temple-meenakshi',
      templeName: 'Arulmigu Meenakshi Sundareswarar Temple',
      location: 'Madurai, Tamil Nadu',
      title: 'Assistant Shiva Archakar & Veda Parayana Purohit',
      ritualSpecialization: [
        'Saiva Agama Diksha',
        'Rudrabhishekam',
        'Vila Puja & Deeparadhana',
        'Veda Parayanam',
      ],
      vedaTraditionRequired: 'Rigveda or Krishna Yajurveda (Saiva Siddhanta Agama knowledge preferred)',
      minExperienceYears: 5,
      remuneration: '₹38,000 – ₹50,000 / month + Official Trust Quarters',
      accommodationProvided: true,
      foodProvided: true,
      description: 'Arulmigu Meenakshi Amman Temple seeks devout, trained Archakar to assist in nitya pujas, Sayaratchai deeparadhana, and participate in grand Chithirai festival rituals.',
      status: 'open',
      postedDate: '2025-01-28',
      applicantsCount: 1,
    },
  ],

  applications: [
    {
      id: 'app-sharma-somnath',
      vacancyId: 'vac-somnath-1',
      vacancyTitle: 'Senior Vedic Archaka & Rudrabhishekam Specialist',
      templeId: 'temple-somnath',
      templeName: 'Shree Somnath Jyotirlinga Temple',
      priestId: 'user-priest-sharma',
      priestName: 'Pandit Rajesh Sharma',
      priestPhone: '+91 98765 43210',
      priestEmail: 'priest.sharma@vedic.org',
      priestExperience: 12,
      priestSkills: [
        'Rudrabhishekam',
        'Ganapathi Homam',
        'Navagraha Shanthi',
        'Veda Parayanam',
      ],
      priestVeda: 'Rigveda - Shakala Shakha',
      priestLanguages: ['Sanskrit', 'Hindi', 'Tamil', 'Telugu'],
      coverNote: 'Namaste. With 12 years of devoted Rigvedic training from Sri Venkateswara Veda Pathashala and extensive experience conducting Laghu Rudra abhishekams in Varanasi and Madurai, I humbly offer my services for Somnath Mahadev.',
      availableFrom: '2025-03-01',
      status: 'shortlisted',
      adminNotes: 'Strong Vedic credentials. Kramanta passed. Verified references from Kashi Vishwanath sub-shrine. Excellent candidate for Laghu Rudra.',
      aiMatchScore: 94,
      aiMatchSummary: 'Exceptional match: Rigveda Kramanta background matches vacancy requirement precisely; 12 years experience exceeds 7-year threshold; verified Rudrabhishekam expertise.',
      submittedAt: '2025-01-20T14:30:00Z',
      updatedAt: '2025-01-22T09:15:00Z',
    },
  ],

  messages: [
    {
      id: 'msg-1',
      applicationId: 'app-sharma-somnath',
      templeId: 'temple-somnath',
      senderId: 'user-admin-somnath',
      senderName: 'Dharmendra Shastri (Board)',
      senderRole: 'admin',
      recipientId: 'user-priest-sharma',
      recipientName: 'Pandit Rajesh Sharma',
      content: 'Pranam Panditji. The Somnath Board has reviewed your Rigveda Kramanta certificate and application. We have shortlisted you for the Senior Archaka position.',
      timestamp: '2025-01-22T09:20:00Z',
      read: true,
    },
    {
      id: 'msg-2',
      applicationId: 'app-sharma-somnath',
      templeId: 'temple-somnath',
      senderId: 'user-priest-sharma',
      senderName: 'Pandit Rajesh Sharma',
      senderRole: 'priest',
      recipientId: 'user-admin-somnath',
      recipientName: 'Dharmendra Shastri (Board)',
      content: 'Har Har Mahadev. Thank you Shastriji. I am deeply honored and ready for the viva-voce and recitation assessment at your convenience.',
      timestamp: '2025-01-22T10:05:00Z',
      read: true,
    },
  ],

  contributorProposals: [
    {
      id: 'prop-1',
      templeId: 'temple-meenakshi',
      templeName: 'Arulmigu Meenakshi Sundareswarar Temple',
      priestId: 'user-priest-sharma',
      priestName: 'Pandit Rajesh Sharma',
      updateType: 'timings',
      proposedData: {
        morning: '04:30 AM – 01:00 PM',
        evening: '04:00 PM – 10:30 PM',
        specialDays: 'Chithirai Thiruvizha: Special continuous queue tokens from 04:00 AM.',
        notes: 'Recommended opening 30 minutes earlier during upcoming festival month for outstation devotees.',
      },
      rationale: 'During the upcoming Chithirai festival month, crowd ingress begins as early as 04:15 AM. Opening sanctum gates 30 minutes earlier will avoid crowd congestion at the South Gopuram.',
      status: 'pending_admin_review',
      submittedAt: '2025-02-14T11:00:00Z',
    },
  ],

  claimRequests: [
    {
      id: 'claim-1',
      templeId: 'temple-varanasi-sankatmochan',
      templeName: 'Sankat Mochan Hanuman Temple',
      applicantUserId: 'user-devotee-1',
      applicantName: 'Ramesh Kumar',
      officialRole: 'Heritage Preservation Volunteer / Liaison',
      phone: '+91 98410 12345',
      email: 'devotee@templeconnect.org',
      verificationDocs: 'Submitted Letter of Recommendation from local Seva Samiti (Ref #VNS-2025-412)',
      status: 'pending',
      submittedAt: '2025-02-10T16:00:00Z',
    },
  ],

  notifications: [
    {
      id: 'notif-1',
      userId: 'user-admin-somnath',
      type: 'application',
      title: 'New Priest Application Received',
      message: 'Pandit Rajesh Sharma submitted an application for Senior Vedic Archaka position.',
      link: '/admin/applications',
      read: false,
      createdAt: '2025-01-20T14:30:00Z',
    },
    {
      id: 'notif-2',
      userId: 'user-priest-sharma',
      type: 'status_change',
      title: 'Application Shortlisted! 🎉',
      message: 'Your application for Senior Vedic Archaka at Shree Somnath Jyotirlinga Temple has been shortlisted.',
      link: '/priest/applications',
      read: false,
      createdAt: '2025-01-22T09:15:00Z',
    },
    {
      id: 'notif-3',
      userId: 'user-admin-meenakshi',
      type: 'contributor_update',
      title: 'Contributor Proposed Temple Update',
      message: 'Pandit Rajesh Sharma proposed revised festival darshan timings for Meenakshi Amman Temple.',
      link: '/admin/contributors',
      read: false,
      createdAt: '2025-02-14T11:00:00Z',
    },
  ],

  auditLogs: [
    {
      id: 'audit-1',
      templeId: 'temple-meenakshi',
      performedBy: 'Sundaram Gurukkal (Trustee)',
      action: 'Grant Contributor Permission',
      details: 'Granted verified contributor permissions to Pandit Rajesh Sharma (Rigvedic Scholar).',
      timestamp: '2025-01-10T10:15:00Z',
    },
    {
      id: 'audit-2',
      templeId: 'temple-somnath',
      performedBy: 'Dharmendra Shastri (Board)',
      action: 'Shortlist Applicant',
      details: 'Shortlisted Pandit Rajesh Sharma for vacancy "Senior Vedic Archaka". AI compatibility score: 94%.',
      timestamp: '2025-01-22T09:15:00Z',
    },
  ],
};
