import { Temple } from '../src/types';

export const initialTemples: Temple[] = [
  // 1. Tirupati (Sri Venkateswara Swamy Temple)
  {
    id: 'temple-tirupati',
    name: 'Sri Venkateswara Swamy Temple (Tirumala)',
    deity: 'Lord Venkateswara (Govinda / Balaji / Srinivasa)',
    city: 'Tirumala, Tirupati',
    state: 'Andhra Pradesh',
    address: 'S Mada St, Tirumala, Tirupati, Andhra Pradesh 517504',
    lat: 13.6833,
    lng: 79.3472,
    description: 'The world-renowned Kaliyuga Vaikuntha temple dedicated to Lord Venkateswara atop the seven sacred peaks of Seshachalam Hills.',
    history: 'Ancient Vaishnava Divya Kshetra mentioned in Sangam works and Rigvedic verses. Extensively patronized by the Pallavas, Cholas, Pandyas, and Vijayanagara emperor Sri Krishnadevaraya, who offered his crowns and gold to the Lord.',
    timings: {
      morning: '03:00 AM – 11:30 AM',
      evening: '12:00 PM – 11:30 PM (Ekantha Seva at midnight)',
      notes: 'Suprabhatam begins at 03:00 AM. Sarva Darshan queues operate continuously through Vaikuntam Queue Complex.',
      specialDays: 'Salakatla & Navaratri Brahmotsavams feature 24-hour continuous darshan.',
    },
    pujas: [
      { id: 'p-t1', name: 'Suprabhata Seva', timing: '03:00 AM', significance: 'Morning awakening prayer to Lord Venkateswara in the sanctum', fee: '₹120' },
      { id: 'p-t2', name: 'Thomala Seva', timing: '03:45 AM', significance: 'Adorning the deity with fragrant sacred flower garlands', fee: '₹220' },
      { id: 'p-t3', name: 'Sahasranamarchana', timing: '04:45 AM', significance: 'Recitation of 1,008 divine names with Tulasi leaves', fee: '₹220' },
      { id: 'p-t4', name: 'Kalyanotsavam', timing: '11:00 AM', significance: 'Grand celestial wedding ceremony of Sri Malayappa Swamy with Sridevi and Bhudevi', fee: '₹1,000' },
      { id: 'p-t5', name: 'Sahastra Deepalankara Seva', timing: '05:30 PM', significance: 'Procession and swing seva amidst 1,000 lit ghee lamps outside the temple', fee: '₹500' },
    ],
    contact: {
      phone: '+91 877 2277777',
      email: 'helpdesk@tirumala.org',
      website: 'https://ttdevasthanams.ap.gov.in',
      trusteeContact: 'TTD Executive Officer Administrative Building, K.T. Road, Tirupati',
    },
    photos: [
      '/images/temples/temple-tirupati.jpg',
    ],
    status: 'representative_verified',
    claimStatus: 'claimed',
    contributors: [],
    events: [
      {
        id: 'ev-t1',
        title: 'Srivari Salakatla Brahmotsavam',
        date: '2026-09-28',
        time: '08:00 AM',
        description: 'Nine-day annual festival featuring Garuda Seva, Rathotsavam, and sacred Chakra Snanam.',
      },
      {
        id: 'ev-t2',
        title: 'Vaikunta Ekadasi Uttara Dwara Darshanam',
        date: '2026-12-21',
        time: '04:00 AM',
        description: 'Pilgrims pass through the sacred Vaikunta Dwaram for the special 10-day period.',
      },
    ],
    dressCode: 'Strict traditional dress code enforced. Men: Dhoti with Kurta or Melchattai (shirtless with angavastram preferred). Women: Saree or Half-Saree or Churidar with Dupatta. Jeans, shorts, and T-shirts strictly prohibited.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 2. Vijayawada Kanaka Durga Ammavaru
  {
    id: 'temple-vijayawada-kanakadurgamma',
    name: 'Sri Durga Malleswara Swamy Varla Devasthanam (Kanaka Durga Temple)',
    deity: 'Goddess Kanaka Durga (Swayambhu Mahishasuramardini) & Sri Malleswara Swamy',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    address: 'Indrakeeladri Hill, Mallikarjunapeta, Vijayawada, Andhra Pradesh 520001',
    lat: 16.5162,
    lng: 80.6067,
    description: 'The celebrated Shakta kshetra perched on the sacred Indrakeeladri hill overlooking the river Krishna, where Mother Kanaka Durga resides as Swayambhu.',
    history: 'Sthala puranam reveals that Arjuna performed intense penance on Indrakeeladri hill to propitiate Lord Shiva and attained the Pasupatastra. Sage Indrakeela meditated here to host the Mother Goddess. Adi Shankaracharya visited the temple and consecrated the auspicious Sri Chakra Yantra to pacify her fiery form.',
    timings: {
      morning: '04:00 AM – 12:30 PM',
      evening: '01:30 PM – 09:30 PM',
      notes: 'Continuous Sarva Darshan open throughout the day. Temple opens early at 03:00 AM during Navaratri.',
      specialDays: 'Dasara Sharannavaratri and Bhavani Deeksha Viramana witness 24-hour special darshan lanes.',
    },
    pujas: [
      { id: 'p-kd1', name: 'Suprabhata Seva', timing: '04:00 AM', significance: 'Morning awakening prayer and Mangala Harathi', fee: '₹100' },
      { id: 'p-kd2', name: 'Khadgamala Archana', timing: '06:00 AM', significance: 'Sacred Shakta hymn chanting with vermilion (kumkum)', fee: '₹250' },
      { id: 'p-kd3', name: 'Kumkumarchana', timing: '07:00 AM – 06:00 PM', significance: 'Devotees participate in individual kumkuma archana to Ammavaru', fee: '₹300' },
      { id: 'p-kd4', name: 'Sri Chandi Homam', timing: '08:30 AM', significance: 'Grand sacrificial fire ritual invoking Durga Saptashati for prosperity and protection', fee: '₹1,500' },
      { id: 'p-kd5', name: 'Nitya Kalyanam', timing: '09:30 AM', significance: 'Celestial wedding of Sri Malleswara Swamy and Kanaka Durga Devi', fee: '₹1,000' },
      { id: 'p-kd6', name: 'Maha Harathi', timing: '09:00 PM', significance: 'Solemn night concluding aarti and pushpanjali', fee: 'Free' },
    ],
    contact: {
      phone: '+91 866 2423600',
      email: 'eo_kanakadurgamma@yahoo.co.in',
      website: 'https://kanakadurgamma.org',
      trusteeContact: 'Executive Officer Office, Indrakeeladri Devasthanam, Vijayawada',
    },
    photos: [
      '/images/temples/temple-vijayawada-kanakadurgamma.jpg',
    ],
    status: 'representative_verified',
    claimStatus: 'claimed',
    contributors: [],
    events: [
      {
        id: 'ev-kd1',
        title: 'Dasara Sharannavaratri Mahotsavam',
        date: '2026-10-10',
        time: '04:00 AM',
        description: 'Ten days of distinct divine alankarams of Ammavaru culminating in the Krishna River Teppotsavam with the celestial Hamsa Vahanam.',
      },
      {
        id: 'ev-kd2',
        title: 'Bhavani Deeksha Viramana',
        date: '2026-12-28',
        time: '05:00 AM',
        description: 'Lakhs of Bhavani devotees wearing red robes congregate to offer Irumudi at the sanctum.',
      },
    ],
    dressCode: 'Strict traditional Indian attire: Dhoti or Kurta-Pyjama for men; Saree, Half-Saree, or Chudidar with Dupatta for women. Shorts, mini-skirts, and sleeveless tops not permitted.',
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 3. Arunachalam (Arulmigu Arunachaleswarar Temple)
  {
    id: 'temple-arunachalam',
    name: 'Arulmigu Arunachaleswarar Temple (Arunachalam / Annamalaiyar)',
    deity: 'Lord Arunachaleswarar (Agni Lingam) & Goddess Unnamalai Amman (Apeethakuchambal)',
    city: 'Thiruvannamalai',
    state: 'Tamil Nadu',
    address: 'Pavazhakundur, Thiruvannamalai, Tamil Nadu 606601',
    lat: 12.2253,
    lng: 79.0677,
    description: 'One of the five sacred Pancha Bhoota Sthalams representing Fire (Agni). The magnificent 25-acre complex lies at the foot of Mount Arunachala, revered as the Shiva Lingam itself.',
    history: 'Celebrated in the hymns of the Shaivite Nayanars. Sthala purana states Lord Shiva appeared as a boundless pillar of blazing light (Jyotirlinga) when Brahma and Vishnu vied for superiority. Consecrated center of Sri Ramana Maharshi and Saint Arunagirinathar.',
    timings: {
      morning: '05:30 AM – 12:30 PM',
      evening: '03:30 PM – 09:30 PM',
      notes: 'Sanctum closes between 12:30 PM and 03:30 PM. Pournami Girivalam pathway around the 14-km hill is open 24 hours.',
    },
    pujas: [
      { id: 'p-ar1', name: 'Ushakkala Puja', timing: '06:00 AM', significance: 'Dawn abhishekam and arati to the Agni Lingam', fee: 'Free' },
      { id: 'p-ar2', name: 'Kalasandhi Puja', timing: '08:00 AM', significance: 'Morning archana with sacred bilva leaves', fee: '₹50' },
      { id: 'p-ar3', name: 'Uchikala Puja', timing: '11:30 AM', significance: 'Midday grand naivedyam and arati', fee: '₹50' },
      { id: 'p-ar4', name: 'Sayaratchai Puja', timing: '06:00 PM', significance: 'Dusk deeparadhana with traditional nadaswaram recital', fee: '₹100' },
      { id: 'p-ar5', name: 'Arthajama Puja', timing: '09:00 PM', significance: 'Night closing puja and palliarai seva', fee: '₹100' },
    ],
    contact: {
      phone: '+91 4175 252438',
      email: 'jointcommissioner_annamalaiyar@hrce.tn.gov.in',
      website: 'https://arunachaleswarartemple.tnhrce.in',
    },
    photos: [
      '/images/temples/temple-arunachalam.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-ar1',
        title: 'Karthigai Deepam Brahmotsavam',
        date: '2026-11-23',
        time: '06:00 PM',
        description: 'The monumental Karthigai Maha Deepam cauldron is lit atop the 2,668-foot peak of Mount Arunachala, visible for over 30 kilometers.',
      },
      {
        id: 'ev-ar2',
        title: 'Pournami Girivalam',
        date: '2026-10-25',
        time: 'All Night',
        description: 'Hundreds of thousands of devotees perform barefoot circumambulation along the 14-km sacred mountain path.',
      },
    ],
    dressCode: 'Traditional attire mandatory. Men: Dhoti or Pyjama with shirt/upper cloth. Women: Saree, Half-Saree, or Churidar with Shawl.',
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 4. Kedarnath
  {
    id: 'temple-kedarnath',
    name: 'Kedarnath Jyotirlinga Temple',
    deity: 'Lord Kedarnath (Shiva Jyotirlinga - Sadashiva)',
    city: 'Kedarnath',
    state: 'Uttarakhand',
    address: 'Kedarnath, Rudraprayag District, Uttarakhand 246445',
    lat: 30.7352,
    lng: 79.0669,
    description: 'The highest and northernmost of the twelve Jyotirlingas, situated at 3,583 meters altitude in the snow-clad Garhwal Himalayas beside the Mandakini River.',
    history: 'Built with colossal interlocking granite slabs. The Pandavas sought Lord Shiva to atone for the Mahabharata war; Shiva assumed the form of a celestial bull whose hump manifested at Kedarnath. Present shrine consecrated by Adi Shankaracharya who attained Mahasamadhi here.',
    timings: {
      morning: '05:00 AM – 01:30 PM',
      evening: '05:00 PM – 09:00 PM',
      notes: 'Temple opens annually on Akshaya Tritiya (April/May) and closes on Bhai Dooj (October/November). During winter, the Utsava Murti is worshipped at Omkareshwar Temple in Ukhimath.',
    },
    pujas: [
      { id: 'p-kn1', name: 'Maha Abhishek', timing: '04:00 AM', significance: 'Sacred early morning bath of the holy triangular rock Jyotirlinga with Panchamrit', fee: '₹1,700' },
      { id: 'p-kn2', name: 'Rudrabhishek', timing: '05:30 AM', significance: 'Continuous recitation of Sri Rudram and Chamakam by Badrinath-Kedarnath Temple Committee Rawals', fee: '₹1,000' },
      { id: 'p-kn3', name: 'Laghu Rudra Puja', timing: '07:00 AM', significance: 'Special Vedic oblations offered in the inner sanctum', fee: '₹600' },
      { id: 'p-kn4', name: 'Sandhya Shringar Aarti', timing: '07:00 PM', significance: 'Evening aarti with divine flowers and musical chants amidst mountain echoes', fee: 'Free' },
    ],
    contact: {
      phone: '+91 135 2741600',
      email: 'bktc.kedarnath@gmail.com',
      website: 'https://badrinath-kedarnath.gov.in',
    },
    photos: [
      '/images/temples/temple-kedarnath.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-kn1',
        title: 'Kedarnath Kapat Opening Ceremony',
        date: '2026-05-02',
        time: '06:00 AM',
        description: 'Sacred opening of the temple doors accompanied by Army bands, flower shower, and the arrival of Lord Kedarnath Doli from Ukhimath.',
      },
      {
        id: 'ev-kn2',
        title: 'Shravan Maas Jalabhishek',
        date: '2026-08-01',
        time: '05:00 AM',
        description: 'Auspicious month of holy offerings of Ganga jal from Gaumukh and Gangotri by Kanwariyas.',
      },
    ],
    dressCode: 'Warm modest clothing suitable for Himalayan sub-zero climate. Footwear, mobile phones, cameras, and leather belts strictly prohibited in the inner Garbhagriha.',
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 5. Nandalur (Sri Soumyanatha Swamy Temple)
  {
    id: 'temple-nandalur',
    name: 'Sri Soumyanatha Swamy Temple (Nandalur)',
    deity: 'Lord Soumyanatha Swamy (Sri Maha Vishnu in standing serene posture)',
    city: 'Nandalur',
    state: 'Andhra Pradesh',
    address: 'Nandalur Village, Rajampet Mandal, Annamayya District, Andhra Pradesh 516150',
    lat: 14.2589,
    lng: 79.1172,
    description: 'An architectural jewel of the 11th century built by the Cholas, featuring 108 intricately carved stone pillars and a sanctum aligned with the rays of the sun on the banks of the Cheyyeru River.',
    history: 'Built by Kulottunga Chola I and patronized by the Kakatiyas, Matsya chiefs, and Vijayanagara monarchs. The Moolavirat of Soumyanatha Swamy is carved from lustrous black granite. A remarkable architectural phenomenon occurs during equinoxes when the morning rays of the sun illuminate the feet and face of the deity.',
    timings: {
      morning: '06:00 AM – 12:00 PM',
      evening: '04:30 PM – 08:30 PM',
      notes: 'Special archana and tirumanjanam performed on every Ekadasi and Sravana Nakshatra.',
    },
    pujas: [
      { id: 'p-nl1', name: 'Suprabhata Seva', timing: '06:00 AM', significance: 'Morning awakening prayer', fee: '₹20' },
      { id: 'p-nl2', name: 'Nitya Archana', timing: '08:30 AM', significance: 'Recitation of Vishnu Sahasranama with sacred tulasi leaves', fee: '₹30' },
      { id: 'p-nl3', name: 'Sahasranamarchana', timing: '10:00 AM', significance: 'Special archana with fragrant flowers', fee: '₹50' },
      { id: 'p-nl4', name: 'Santhana Gopala Homam', timing: '11:00 AM', significance: 'Auspicious ritual for marital harmony and progeny blessing', fee: '₹250' },
      { id: 'p-nl5', name: 'Sayaratchai Harathi', timing: '06:30 PM', significance: 'Evening camphor light offering with bells', fee: 'Free' },
    ],
    contact: {
      phone: '+91 8567 222123',
      email: 'soumyanatha.nandalur@apendowments.gov.in',
      website: 'https://aptemples.ap.gov.in',
    },
    photos: [
      '/images/temples/temple-nandalur.webp',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-nl1',
        title: 'Soumyanatha Swamy Annual Brahmotsavams',
        date: '2026-04-18',
        time: '08:00 AM',
        description: 'Seven-day Chaitra Masa festival featuring Garuda Vahanam, Hamsa Vahanam, and Rathotsavam.',
      },
      {
        id: 'ev-nl2',
        title: 'Vaikunta Ekadasi',
        date: '2026-12-21',
        time: '05:00 AM',
        description: 'Special Uttara Dwara Pravesham for thousands of devotees from Rayalaseema.',
      },
    ],
    dressCode: 'Traditional Indian attire: Dhoti/Kurta for men; Saree/Salwar for women.',
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 6. Ontimitta (Sri Kodandarama Swamy Temple)
  {
    id: 'temple-ontimitta',
    name: 'Sri Kodandarama Swamy Temple (Ontimitta / Vontimitta)',
    deity: 'Sri Kodandarama Swamy (Rama holding Kodandam bow, Sita Devi & Lakshmana on single stone)',
    city: 'Vontimitta (Ontimitta)',
    state: 'Andhra Pradesh',
    address: 'Vontimitta, Kadapa-Tirupati Highway, YSR Kadapa District, Andhra Pradesh 516213',
    lat: 14.3941,
    lng: 79.0275,
    description: 'Famed as the "Andhra Bhadrachalam", this 14th-century Vijayanagara architectural masterpiece houses a unique monolithic deity and is deeply linked with the composition of Andhra Maha Bhagavatham.',
    history: 'Built by Vijayanagara rulers Bukka Raya I and expanded by Krishnadevaraya. The sanctum features a monolithic stone carved with Rama, Sita, and Lakshmana without Hanuman (depicting the Kishkindha Kanda phase before meeting Hanuman). Saint-poet Bammera Potana composed his Telugu epic Andhra Maha Bhagavatham in this courtyard and dedicated it to Sri Rama.',
    timings: {
      morning: '06:00 AM – 01:00 PM',
      evening: '04:00 PM – 08:30 PM',
      notes: 'Temple administered under Tirumala Tirupati Devasthanams (TTD).',
    },
    pujas: [
      { id: 'p-om1', name: 'Suprabhatam', timing: '06:00 AM', significance: 'Morning awakening prayer', fee: '₹30' },
      { id: 'p-om2', name: 'Nitya Sahasranama Archana', timing: '08:30 AM', significance: 'Recitation of sacred Vishnu Sahasranama with Tulasi', fee: '₹50' },
      { id: 'p-om3', name: 'Kalyanotsavam', timing: '10:30 AM', significance: 'Celestial wedding ceremony of Sita Rama', fee: '₹300' },
      { id: 'p-om4', name: 'Sayaratchai Deepam', timing: '06:30 PM', significance: 'Evening camphor arati and Vishnu stuti', fee: 'Free' },
    ],
    contact: {
      phone: '+91 8568 288333',
      email: 'helpdesk@tirumala.org',
      website: 'https://ttdevasthanams.ap.gov.in',
    },
    photos: [
      '/images/temples/temple-ontimitta.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-om1',
        title: 'State Festival Sri Rama Navami Brahmotsavams',
        date: '2026-03-27',
        time: '07:00 PM',
        description: 'Andhra Pradesh state festival featuring the celestial Sita Rama Kalyanam conducted on Chaitra Suddha Pournami night under the moonlight, attended by the Chief Minister presenting silk vastrams and pearls.',
      },
    ],
    dressCode: 'Traditional dress mandatory: Dhoti or Kurta for men; Saree or Chudidar with Dupatta for women.',
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 7. Srikalahasthi (Srikalahasteeswara Temple)
  {
    id: 'temple-srikalahasthi',
    name: 'Srikalahasteeswara Temple (Srikalahasthi)',
    deity: 'Lord Srikalahasteeswara (Vayu Lingam) & Goddess Gnanaprasunambika',
    city: 'Srikalahasti',
    state: 'Andhra Pradesh',
    address: 'Srikalahasti, Tirupati District, Andhra Pradesh 517644',
    lat: 13.7498,
    lng: 79.7037,
    description: 'The ancient Pancha Bhoota Kshetra representing the Air / Wind element (Vayu Lingam), world-renowned for Rahu-Ketu Sarpa Dosha Nivarana pujas on the banks of the Swarnamukhi River.',
    history: 'Constructed by the Pallavas in the 5th century and greatly patronized by the Cholas and Vijayanagara Emperor Krishnadevaraya who built the hundred-pillared mandapam. The flame in the sanctum flutters perpetually even with all doors closed, manifesting the Vayu Lingam. Named after Sri (spider), Kala (snake), and Hasti (elephant) who worshipped Lord Shiva with pure devotion.',
    timings: {
      morning: '06:00 AM – 09:00 PM',
      evening: 'Open continuously all day',
      notes: 'Rahu Ketu Pujas are performed continuously in batches from 06:30 AM to 06:00 PM.',
    },
    pujas: [
      { id: 'p-sk1', name: 'Rahu Ketu Sarpa Dosha Nivarana Puja', timing: '06:30 AM – 06:00 PM', significance: 'World-famous Vedic remedy puja for clearing ancestral, astrological, and marital doshas', fee: '₹500 / ₹1,500 / ₹2,500' },
      { id: 'p-sk2', name: 'Rudrabhishekam', timing: '07:30 AM', significance: 'Sacred abhishekam of the Vayu Lingam with panchamrit and bilva leaves', fee: '₹600' },
      { id: 'p-sk3', name: 'Gomatha Puja', timing: '06:00 AM', significance: 'Worship of Kamadhenu cow at the temple entrance', fee: '₹100' },
      { id: 'p-sk4', name: 'Pallaki Seva', timing: '08:30 PM', significance: 'Night palanquin procession of the Utsava deities', fee: '₹200' },
    ],
    contact: {
      phone: '+91 8578 222240',
      email: 'eo_srikalahasti@yahoo.co.in',
      website: 'https://srikalahasthitemple.com',
    },
    photos: [
      '/images/temples/temple-srikalahasthi.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-sk1',
        title: 'Maha Shivaratri Brahmotsavam',
        date: '2026-03-08',
        time: 'All Night',
        description: '13-day grand festival featuring Nandi Vahanam procession, Giri Pradakshina, and Rathotsavam with millions of pilgrims.',
      },
    ],
    dressCode: 'Strict traditional Indian attire. Men: Dhoti or Kurta-Pyjama (must remove upper shirts for sanctum abhishekam and Rahu-Ketu pujas). Women: Saree or Chudidar with Dupatta.',
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 8. Srisailam (Sri Bhramaramba Mallikarjuna Swamy Temple)
  {
    id: 'temple-srisailam',
    name: 'Sri Bhramaramba Mallikarjuna Swamy Temple (Srisailam)',
    deity: 'Lord Mallikarjuna Swamy (Shiva Jyotirlinga) & Goddess Bhramaramba Devi (Maha Shakti Peetham)',
    city: 'Srisailam',
    state: 'Andhra Pradesh',
    address: 'Srisailam Devasthanam, Srisailam, Nandyal District, Andhra Pradesh 518101',
    lat: 16.0741,
    lng: 78.8686,
    description: 'One of the rarest shrines on earth where a Jyotirlinga of Lord Shiva and an Ashtadasa Maha Shakti Peetha of Mother Sati reside together atop the Nallamala forest hills beside Krishna River.',
    history: 'Dating back over two millennia, patronized by the Satavahanas, Ikshvakus, Kakatiyas (Queen Rudrama Devi), and Chhatrapati Shivaji Maharaj who built the northern gopuram. Devotees are uniquely permitted Sparsha Darshanam (to physically touch the holy Jyotirlinga during Abhishekam).',
    timings: {
      morning: '04:30 AM – 03:30 PM',
      evening: '06:00 PM – 10:00 PM',
      notes: 'Sparsha Darshanam (touching the Lingam) occurs during morning and evening slots with online token.',
    },
    pujas: [
      { id: 'p-sr1', name: 'Sparsha Darshanam & Abhishekam', timing: '06:30 AM', significance: 'Direct touching and bathing of the holy Jyotirlinga with holy water and bilva patra', fee: '₹500' },
      { id: 'p-sr2', name: 'Bhramaramba Devi Kumkumarchana', timing: '07:00 AM – 02:00 PM', significance: 'Special vermilion archana at the Maha Shakti Peetham', fee: '₹200' },
      { id: 'p-sr3', name: 'Maha Rudra Homam', timing: '08:30 AM', significance: 'Vedic fire ritual invoking 11 Anuvakas of Sri Rudram', fee: '₹1,116' },
      { id: 'p-sr4', name: 'Nitya Kalyanam', timing: '07:00 PM', significance: 'Divine wedding ritual of Mallikarjuna Swamy and Bhramaramba Devi', fee: '₹1,000' },
    ],
    contact: {
      phone: '+91 8524 288888',
      email: 'support@srisailadevasthanam.org',
      website: 'https://srisailadevasthanam.org',
    },
    photos: [
      '/images/temples/temple-srisailam.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-sr1',
        title: 'Maha Shivaratri Brahmotsavam',
        date: '2026-03-08',
        time: 'All Night',
        description: 'Seven-day grand festival with Lingodbhava Kaala Rudrabhishekam and Pagalankarana (tying of sacred turban cloth around the vimana).',
      },
      {
        id: 'ev-sr2',
        title: 'Ugadi Mahotsavam',
        date: '2026-03-20',
        time: '06:00 AM',
        description: 'Traditional Telugu and Kannada New Year festivities with lakhs of Kannada pilgrims arriving on padayatra.',
      },
    ],
    dressCode: 'Strict Vedic dress code: Men must wear Dhoti & Uttariyam without shirt during Sparsha Darshan. Women must wear Saree or Salwar with Dupatta.',
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 9. Simhachalam (Sri Varaha Lakshmi Narasimha Swamy Temple)
  {
    id: 'temple-simhachalam',
    name: 'Sri Varaha Lakshmi Narasimha Swamy Temple (Simhachalam)',
    deity: 'Lord Varaha Lakshmi Narasimha Swamy (Narasimha Avatar)',
    city: 'Simhachalam, Visakhapatnam',
    state: 'Andhra Pradesh',
    address: 'Simhachalam Hill, Visakhapatnam, Andhra Pradesh 530028',
    lat: 17.7665,
    lng: 83.2505,
    description: 'Perched 800 feet high on the Simhachalam hill, this ancient 11th-century temple features the Lord covered in continuous consecrated sandalwood paste throughout the year to soothe his celestial ferocity.',
    history: 'Built by King Narasimhadeva I of the Eastern Ganga dynasty and patronized by Sri Krishnadevaraya. The presiding deity is an amalgamation of the Varaha (boar) and Narasimha (lion) avatars. The sandalwood paste is scraped away only once a year on Akshaya Tritiya for the sacred 12-hour Chandanotsavam Nijaroopa Darshanam.',
    timings: {
      morning: '07:00 AM – 04:00 PM',
      evening: '06:00 PM – 09:00 PM',
      notes: 'Continuous darshan throughout the day. Sanctum closes briefly for Rajabhogam at 11:30 AM.',
    },
    pujas: [
      { id: 'p-sc1', name: 'Suprabhata Seva', timing: '05:00 AM', significance: 'Morning awakening prayer', fee: '₹100' },
      { id: 'p-sc2', name: 'Ashtottara Shatanama Archana', timing: '08:00 AM', significance: 'Recitation of 108 holy names of Lord Narasimha', fee: '₹50' },
      { id: 'p-sc3', name: 'Nitya Kalyanam', timing: '09:30 AM', significance: 'Celestial wedding ceremony of the Lord with Lakshmi Devi', fee: '₹1,000' },
      { id: 'p-sc4', name: 'Sahasranamarchana', timing: '10:30 AM', significance: '1000 divine names chanting with Tulasi', fee: '₹200' },
      { id: 'p-sc5', name: 'Sayana Seva', timing: '08:30 PM', significance: 'Lullaby and resting ritual of the Lord', fee: '₹100' },
    ],
    contact: {
      phone: '+91 891 2715400',
      email: 'simhachalamdevasthanam@gmail.com',
      website: 'https://simhachalamdevasthanam.org',
    },
    photos: [
      '/images/temples/temple-simhachalam.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-sc1',
        title: 'Chandanotsavam (Nijaroopa Darshanam)',
        date: '2026-05-02',
        time: '04:00 AM',
        description: 'The sole day of the year on Akshaya Tritiya when the sandalwood paste is ceremonially removed and devotees behold the real form of the deity.',
      },
      {
        id: 'ev-sc2',
        title: 'Giri Pradakshina',
        date: '2026-07-29',
        time: '02:00 PM',
        description: 'Over 300,000 devotees walk the 32-km circumference of the Simhachalam hill range on Ashadha Pournami.',
      },
    ],
    dressCode: 'Traditional Indian attire: Dhoti/Kurta for men; Saree/Half-Saree/Chudidar with Dupatta for women.',
    createdAt: '2024-01-09T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 10. Yadadri (Sri Lakshmi Narasimha Swamy Temple)
  {
    id: 'temple-yadadri',
    name: 'Sri Lakshmi Narasimha Swamy Temple (Yadadri / Yadagirigutta)',
    deity: 'Lord Pancha Narasimha Swamy (Jwala, Yogananda, Gandabherunda, Ugra, and Lakshminarasimha)',
    city: 'Yadagirigutta (Yadadri)',
    state: 'Telangana',
    address: 'Yadadri Hill, Yadagirigutta, Telangana 508115',
    lat: 17.5888,
    lng: 78.9405,
    description: 'The revered Pancha Narasimha cave shrine on a hillock, reconstructed into an architectural marvel of Dravidian craft using 250,000 tonnes of traditional black granite (Krishna Shila).',
    history: 'Sage Yadarishi performed penance here to behold Lord Narasimha. The Lord granted darshan in five manifestations inside the natural cave. The modern temple was rebuilt under master sthapathis adhering to Agama and Shilpa Shastra without using cement.',
    timings: {
      morning: '04:00 AM – 01:30 PM',
      evening: '03:00 PM – 09:30 PM',
      notes: 'Morning Suprabhatam starts at 04:00 AM; Nijabhishekam at 05:30 AM.',
    },
    pujas: [
      { id: 'p-yd1', name: 'Suprabhatam', timing: '04:00 AM', significance: 'Morning awakening hymns to Lord Narasimha', fee: '₹50' },
      { id: 'p-yd2', name: 'Nijabhishekam', timing: '05:30 AM', significance: 'Panchamrita abhishekam of the Swayambhu cave idols', fee: '₹500' },
      { id: 'p-yd3', name: 'Nitya Kalyana Mahotsavam', timing: '09:30 AM', significance: 'Celestial wedding ceremony of Lakshmi and Narasimha', fee: '₹1,500' },
      { id: 'p-yd4', name: 'Sudarshana Homam', timing: '08:30 AM', significance: 'Sacred fire oblation with the Sudarshana Yantra', fee: '₹1,116' },
      { id: 'p-yd5', name: 'Sahasranamarchana', timing: '10:30 AM', significance: 'Chanting 1000 names with sacred Tulasi leaves', fee: '₹200' },
      { id: 'p-yd6', name: 'Shayanotsavam', timing: '09:00 PM', significance: 'Night closing arati and resting seva', fee: '₹100' },
    ],
    contact: {
      phone: '+91 8685 236622',
      email: 'eoyadagirigutta@gmail.com',
      website: 'https://yadadritemple.telangana.gov.in',
    },
    photos: [
      '/images/temples/temple-yadadri.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-yd1',
        title: 'Annual Brahmotsavam',
        date: '2026-03-02',
        time: '08:00 AM',
        description: '11-day festival from Phalguna Shuddha Padyami with celestial wedding and Divya Vimana Ratha Yatra.',
      },
      {
        id: 'ev-yd2',
        title: 'Narasimha Jayanthi',
        date: '2026-05-19',
        time: '06:00 PM',
        description: 'Special dusk abhishekam commemorating the incarnation of Lord Narasimha.',
      },
    ],
    dressCode: 'Traditional Indian attire mandatory: Dhoti or Kurta-Pyjama for men; Saree or Chudidar with Dupatta for women.',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 11. Bhadrachalam (Sri Seetha Ramachandra Swamy Temple)
  {
    id: 'temple-bhadrachalam',
    name: 'Sri Seetha Ramachandra Swamy Temple (Bhadrachalam)',
    deity: 'Lord Vaikuntha Rama (holding Shankha, Chakra, Bow and Arrow) with Sita Devi and Lakshmana',
    city: 'Bhadrachalam',
    state: 'Telangana',
    address: 'Bhadrachalam, Bhadradri Kothagudem District, Telangana 507111',
    lat: 17.6688,
    lng: 80.8936,
    description: 'The supreme Rama kshetra nestled on the banks of the sacred Godavari River in the Dandakaranya forest, immortalized by the divine devotion of Bhakta Ramadasu.',
    history: 'Lord Vishnu manifested as Vaikuntha Rama with four hands (holding Shankha and Chakra) to fulfill his promise to sage Bhadra. In the 17th century, Tahsildar Kancharla Gopanna (Bhakta Ramadasu) constructed the temple and crafted peerless gem-studded jewels (Chintaku Pathakam, Pachala Haram) for the deities, enduring 12 years in Golconda prison before Lord Rama redeemed him.',
    timings: {
      morning: '04:30 AM – 01:00 PM',
      evening: '03:00 PM – 09:00 PM',
      notes: 'Suprabhatam at 04:30 AM; Nitya Kalyanam performed daily at 09:30 AM.',
    },
    pujas: [
      { id: 'p-bc1', name: 'Suprabhata Seva', timing: '04:30 AM', significance: 'Morning awakening hymns and arati', fee: '₹50' },
      { id: 'p-bc2', name: 'Abhishekam', timing: '07:00 AM', significance: 'Holy bath of the Moolavirat with panchamrit', fee: '₹200' },
      { id: 'p-bc3', name: 'Nitya Kalyana Utsavam', timing: '09:30 AM', significance: 'Daily celestial wedding of Sri Rama and Sita Devi at the Kalyana Mandapam', fee: '₹1,000' },
      { id: 'p-bc4', name: 'Sahasranama Archana', timing: '10:30 AM', significance: 'Chanting 1000 names of Lord Rama', fee: '₹100' },
      { id: 'p-bc5', name: 'Rajabhogam & Pavalimpu Seva', timing: '08:30 PM', significance: 'Night naivedyam and lullaby for the divine couple', fee: '₹100' },
    ],
    contact: {
      phone: '+91 8743 232428',
      email: 'eobhadrachalam@gmail.com',
      website: 'https://bhadrachalam.telangana.gov.in',
    },
    photos: [
      '/images/temples/temple-bhadrachalam.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-bc1',
        title: 'Sri Rama Navami Vasanthotsavam',
        date: '2026-03-27',
        time: '10:00 AM',
        description: 'Telangana state celebration of the celestial wedding of Lord Rama and Sita Devi with pearls (Mutyala Talambralu) presented by the State Government.',
      },
      {
        id: 'ev-bc2',
        title: 'Vaikunta Ekadasi Teppotsavam',
        date: '2026-12-21',
        time: '05:00 PM',
        description: 'Mukkoti Ekadasi celebrations featuring a magnificent boat procession in the Godavari River and Uttara Dwara Darshanam.',
      },
    ],
    dressCode: 'Traditional Indian attire: Dhoti or Kurta-Pyjama for men; Saree or Chudidar with Dupatta for women.',
    createdAt: '2024-01-11T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 12. Ramanathaswamy Temple (Rameswaram)
  {
    id: 'temple-ramanathaswamy',
    name: 'Arulmigu Ramanathaswamy Temple (Rameswaram)',
    deity: 'Lord Ramanathaswamy (Ramalinga Jyotirlinga) & Goddess Parvathavardhini',
    city: 'Rameswaram',
    state: 'Tamil Nadu',
    address: 'Rameswaram, Ramanathapuram District, Tamil Nadu 623526',
    lat: 9.2881,
    lng: 79.3174,
    description: 'One of the four sacred Char Dham shrines and one of the 12 Jyotirlingas, featuring 22 consecrated teertham wells and the longest carved pillared corridor in the world.',
    history: 'Consecrated by Lord Rama and Mother Sita to atone for killing Ravana. Sita sculpted the sand Ramalingam while Hanuman brought the Vishwalingam from Mount Kailash. The third corridor built by the Setupati kings contains 1,212 granite pillars stretching 197 meters.',
    timings: {
      morning: '05:00 AM – 01:00 PM',
      evening: '03:00 PM – 09:00 PM',
      notes: 'Spatika Linga darshan held from 05:00 AM to 06:00 AM. Snanam in the 22 holy Teerthams takes approximately 1 hour.',
    },
    pujas: [
      { id: 'p-rm1', name: 'Spatika Linga Darshanam', timing: '05:00 AM – 06:00 AM', significance: 'Early dawn darshan of the transparent crystal Spatika Lingam consecrated by Adi Shankaracharya', fee: '₹50' },
      { id: 'p-rm2', name: 'Thiruvanandal Puja', timing: '05:30 AM', significance: 'Morning awakening prayer and first deeparadhana', fee: '₹50' },
      { id: 'p-rm3', name: 'Kala Santhi Puja', timing: '07:00 AM', significance: 'Morning milk and sandal abhishekam', fee: '₹100' },
      { id: 'p-rm4', name: 'Sayaratchai Puja', timing: '06:00 PM', significance: 'Dusk deeparadhana with classical instrumental music', fee: '₹100' },
      { id: 'p-rm5', name: 'Arthajama Puja', timing: '08:30 PM', significance: 'Night closing puja and palanquin procession to the Palli Arai', fee: '₹100' },
      { id: 'p-rm6', name: '22 Teertham Snanam', timing: '06:00 AM – 12:00 PM', significance: 'Purification bath from 22 holy wells inside the temple complex', fee: '₹25' },
    ],
    contact: {
      phone: '+91 4573 221223',
      email: 'rameswaramtemple@tnhrce.in',
      website: 'https://rameswaramtemple.tnhrce.in',
    },
    photos: [
      '/images/temples/temple-ramanathaswamy.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-rm1',
        title: 'Maha Shivaratri Festival',
        date: '2026-03-08',
        time: 'All Night',
        description: 'Ten-day celebration culminating in all-night abhishekam and the silver car procession of Lord Ramanathaswamy.',
      },
      {
        id: 'ev-rm2',
        title: 'Thirukalyanam (Aadi Thirukalyanam)',
        date: '2026-08-04',
        time: '08:00 AM',
        description: 'Celestial wedding of Goddess Parvathavardhini and Lord Ramanathaswamy with coastal car festival.',
      },
    ],
    dressCode: 'Strict traditional attire. Men: Dhoti or Pyjama (must remove shirts/vests before entering the sanctum). Women: Saree or Chudidar with Dupatta. Wet clothes are strictly prohibited inside the main sanctum after taking bath in the 22 teerthams (dry clothes must be worn).',
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 13. Madurai (Arulmigu Meenakshi Sundareswarar Temple)
  {
    id: 'temple-meenakshi',
    name: 'Arulmigu Meenakshi Sundareswarar Temple (Madurai)',
    deity: 'Goddess Meenakshi & Lord Sundareswarar (Shiva)',
    city: 'Madurai',
    state: 'Tamil Nadu',
    address: 'Madurai Main, Madurai, Tamil Nadu 625001',
    lat: 9.9195,
    lng: 78.1193,
    description: 'Historic architectural marvel located on the southern bank of the Vaigai River, world-famous for its 14 towering sculptured gopurams, Thousand Pillar Hall, and living Saivite heritage.',
    history: 'Built during the Pandyan era and expanded during the 16th-17th century Nayakar rule by King Tirumala Nayaka. Celebrates the divine sovereign rule and cosmic wedding of warrior Goddess Meenakshi with Lord Sundareswarar.',
    timings: {
      morning: '05:00 AM – 12:30 PM',
      evening: '04:00 PM – 10:00 PM',
      notes: 'Palli Arai Deeparadhana performed every evening at 09:30 PM with golden palanquin procession.',
    },
    pujas: [
      { id: 'p-m1', name: 'Thiruvanandal Puja', timing: '05:00 AM', significance: 'Morning awakening prayer and first darshan', fee: 'Free' },
      { id: 'p-m2', name: 'Vila Puja & Kalasandhi', timing: '06:30 AM', significance: 'Solemn morning abhishekam and archana', fee: '₹250' },
      { id: 'p-m3', name: 'Uchikalam Puja', timing: '11:00 AM', significance: 'Midday grand offering and deeparadhana', fee: '₹150' },
      { id: 'p-m4', name: 'Sayaratchai Puja', timing: '06:00 PM', significance: 'Dusk arati with nadaswaram recital', fee: '₹200' },
      { id: 'p-m5', name: 'Palli Arai Puja', timing: '09:30 PM', significance: 'Night ceremonial procession of Lord Sundareswarar to Goddess Meenakshi sanctum', fee: '₹500' },
    ],
    contact: {
      phone: '+91 452 2344360',
      email: 'jointcommissioner@maduraimeenakshi.org',
      website: 'https://maduraimeenakshi.hrce.tn.gov.in',
    },
    photos: [
      '/images/temples/temple-meenakshi.jpg',
    ],
    status: 'representative_verified',
    contributors: ['user-priest-sharma'],
    events: [
      {
        id: 'ev-m1',
        title: 'Chithirai Thiruvizha (Celestial Wedding)',
        date: '2026-04-20',
        time: '08:00 AM',
        description: 'Grand annual festival featuring Meenakshi Thirukalyanam and chariot procession around the historic Masi streets.',
      },
      {
        id: 'ev-m2',
        title: 'Navaratri Golu & Special Alankaram',
        date: '2026-10-12',
        time: '05:30 PM',
        description: 'Nine nights of divine alankarams of Amman displayed in the Thousand Pillar Hall.',
      },
    ],
    dressCode: 'Traditional Indian attire mandatory: Dhoti or Pyjama with shirt for men; Saree or Salwar with Dupatta for women.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 14. Udupi Sri Krishna Temple (Sri Krishna Matha)
  {
    id: 'temple-udupi-srikrishna',
    name: 'Sri Krishna Matha / Temple (Udupi)',
    deity: 'Lord Balakrishna (Kadagolu Krishna with churning rod) & Mukhyaprana (Hanuman)',
    city: 'Udupi',
    state: 'Karnataka',
    address: 'Car Street, Sri Krishna Temple Complex, Udupi, Karnataka 576101',
    lat: 13.3409,
    lng: 74.7523,
    description: 'The epicenter of Dvaita Vedanta founded by Jagadguru Sri Madhvacharya in the 13th century, where Lord Balakrishna is viewed exclusively through the nine-holed silver window (Kanakana Kindi).',
    history: 'Sri Madhvacharya retrieved the consecrated idol of Balakrishna encased in Gopichandana clay from a merchant ship off Malpe beach. The Lord turned around to face west towards the outer wall to grant darshan to his devoted saint-poet Kanakadasa. The shrine is administered in rotation every two years by the pontiffs of the Ashta Mathas (Paryaya system).',
    timings: {
      morning: '05:00 AM – 11:00 AM',
      evening: '05:00 PM – 09:00 PM',
      notes: 'Nirmalya Visarjana darshan begins at 05:30 AM. Free holy Anna Santharpana (prasadam lunch) served to all devotees daily.',
    },
    pujas: [
      { id: 'p-ud1', name: 'Nirmalya Visarjana Puja', timing: '05:30 AM', significance: 'Morning removal of previous day garlands and holy bath', fee: 'Free' },
      { id: 'p-ud2', name: 'Ushakala Puja', timing: '06:00 AM', significance: 'Dawn offering with fresh milk and butter', fee: 'Free' },
      { id: 'p-ud3', name: 'Panchamrutha Abhisheka', timing: '08:30 AM', significance: 'Ritual bathing with milk, curd, ghee, honey, and jaggery', fee: '₹250' },
      { id: 'p-ud4', name: 'Mahapuja', timing: '10:00 AM', significance: 'Grand noon offering and arati with golden palanquin', fee: '₹500' },
      { id: 'p-ud5', name: 'Chamara Seva & Ratri Puja', timing: '07:30 PM', significance: 'Night whisk waving ritual with Vedic chanting', fee: '₹200' },
    ],
    contact: {
      phone: '+91 820 2520598',
      email: 'paryaya@udupisrikrishnamatha.org',
      website: 'https://udupisrikrishnamatha.org',
    },
    photos: [
      '/images/temples/temple-udupi-srikrishna.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-ud1',
        title: 'Biennial Paryaya Mahotsava',
        date: '2026-01-18',
        time: '03:00 AM',
        description: 'The ancient historic handover of worship rights among the pontiffs of the Ashta Mathas with grand night processions on Car Street.',
      },
      {
        id: 'ev-ud2',
        title: 'Sri Krishna Janmashtami & Vittal Pindi',
        date: '2026-09-04',
        time: 'All Day',
        description: 'Grand celebrations of the Lord birth with clay idol procession and traditional Huli Vesha folk dance.',
      },
    ],
    dressCode: 'Traditional Indian attire. Men must remove shirts, t-shirts, and vests before stepping into the inner sanctum. Saree or Salwar with Dupatta for women.',
    createdAt: '2024-01-13T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 15. Dwaraka (Dwarkadhish Temple / Jagat Mandir)
  {
    id: 'temple-dwarka',
    name: 'Dwarkadhish Temple (Jagat Mandir, Dwaraka)',
    deity: 'Lord Dwarkadhish (Trivikrama form of Lord Krishna with four arms)',
    city: 'Dwarka',
    state: 'Gujarat',
    address: 'Dwarka, Devbhumi Dwarka District, Gujarat 361335',
    lat: 22.2376,
    lng: 68.9678,
    description: 'One of the four supreme Char Dham pilgrimage kshetras and one of the seven Sapta Puris (Moksha cities), situated where the Gomti River enters the Arabian Sea.',
    history: 'Originally established by Vajranabha, great-grandson of Lord Krishna, over the ruins of Hari Griha (Krishna residential palace). The 5-storey sandstone main shrine rises 78 meters high supported by 72 exquisitely carved pillars, hoisting a 52-yard flag (Dhwaja) that is changed five times daily.',
    timings: {
      morning: '06:30 AM – 01:00 PM',
      evening: '05:00 PM – 09:30 PM',
      notes: 'Mangala Aarti at 06:30 AM; Shayan Aarti at 08:30 PM. Sanctum closes for bhog between 01:00 PM and 05:00 PM.',
    },
    pujas: [
      { id: 'p-dw1', name: 'Mangala Aarti', timing: '06:30 AM', significance: 'First auspicious morning arati of King Dwarkadhish', fee: 'Free' },
      { id: 'p-dw2', name: 'Shringar Aarti', timing: '08:00 AM', significance: 'Royal royal dressing and ornament adornment', fee: 'Free' },
      { id: 'p-dw3', name: 'Snan Bhog', timing: '10:30 AM', significance: 'Holy bath ritual and dry fruit offering', fee: '₹150' },
      { id: 'p-dw4', name: 'Sandhya Aarti', timing: '07:30 PM', significance: 'Dusk arati with conch and drum resonance', fee: 'Free' },
      { id: 'p-dw5', name: 'Dhwaja Arohan Seva', timing: 'Five times daily', significance: 'Ceremonial hoisting of the 52-yard flag atop the temple spire', fee: 'Booking required' },
    ],
    contact: {
      phone: '+91 2892 234090',
      email: 'dwarkadhishtemple@gujarat.gov.in',
      website: 'https://dwarkadhish.org',
    },
    photos: [
      '/images/temples/temple-dwarka.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-dw1',
        title: 'Krishna Janmashtami',
        date: '2026-09-04',
        time: 'All Night',
        description: 'Colossal celebration in the Lord own capital city with midnight Janmotsav and Maha Aarti.',
      },
      {
        id: 'ev-dw2',
        title: 'Annakoot Mahotsav',
        date: '2026-11-10',
        time: '11:00 AM',
        description: 'Offering of 56 varieties of sweets (Chhappan Bhog) to Dwarkadhish on Diwali New Year.',
      },
    ],
    dressCode: 'Modest traditional Indian clothing. Electronic devices, mobiles, and leather accessories must be deposited at the free cloak counter.',
    createdAt: '2024-01-14T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 16. Sri Padmanabhaswamy Temple
  {
    id: 'temple-padmanabhaswamy',
    name: 'Sree Padmanabhaswamy Temple (Thiruvananthapuram)',
    deity: 'Lord Padmanabhaswamy (Maha Vishnu in Anantha Sayanam posture on Adi Shesha)',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    address: 'West Nada, East Fort, Pazhavangadi, Thiruvananthapuram, Kerala 695023',
    lat: 8.4831,
    lng: 76.9436,
    description: 'The royal 108 Divya Desam shrine where the 18-foot Moolavirat of Lord Vishnu reclines on the serpent Adi Shesha, viewed through three separate sanctum doorways.',
    history: 'Celebrated in Sangam literature and Divya Prabandham. In 1750 CE, Maharajah Marthanda Varma performed Thrippadi Danam, surrendering his entire Travancore kingdom to Lord Padmanabha and ruling as His humble servant ("Padmanabha Dasa"). The deity is sculpted out of 12,008 Salagrama stones.',
    timings: {
      morning: '03:15 AM – 12:00 PM',
      evening: '05:00 PM – 07:20 PM',
      notes: 'Specific intermittent darshan slots: 03:15–04:15 AM, 06:30–07:00 AM, 08:30–10:00 AM, 10:30–11:15 AM, 11:45 AM–12:00 PM, 05:00–06:15 PM, 06:45–07:20 PM.',
    },
    pujas: [
      { id: 'p-pn1', name: 'Nirmalya Darshanam', timing: '03:15 AM – 04:15 AM', significance: 'First auspicious early morning darshan of the day', fee: '₹50' },
      { id: 'p-pn2', name: 'Usha Puja', timing: '06:30 AM', significance: 'Morning awakening prayer and butter offering', fee: 'Free' },
      { id: 'p-pn3', name: 'Pantheeradi', timing: '08:30 AM', significance: 'Solemn midway morning archana and naivedyam', fee: '₹150' },
      { id: 'p-pn4', name: 'Sayaratcha Deeparadhana', timing: '06:30 PM', significance: 'Evening camphor light arati in the sanctum', fee: 'Free' },
      { id: 'p-pn5', name: 'Paal Payasam Nivedyam', timing: '11:00 AM', significance: 'Offering of sacred milk sweet rice pudding consecrated for the Lord', fee: '₹120' },
    ],
    contact: {
      phone: '+91 471 2450233',
      email: 'info@spst.in',
      website: 'https://spst.in',
    },
    photos: [
      '/images/temples/temple-padmanabhaswamy.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-pn1',
        title: 'Panguni & Alpashi Aaraattu Procession',
        date: '2026-04-02',
        time: '04:30 PM',
        description: 'The royal sword-bearing procession led by the titular Maharaja to the Arabian Sea at Shanghumugham beach for the sacred Aaraattu holy immersion.',
      },
      {
        id: 'ev-pn2',
        title: 'Murajapam & Laksha Deepam',
        date: '2026-01-14',
        time: '06:00 PM',
        description: 'Vedic recitation festival conducted once every six years culminating in 100,000 oil lamps illuminating the gopuram.',
      },
    ],
    dressCode: 'Strict ancient Travancore Vedic code strictly enforced. Men: Mundu (dhoti) worn around the waist without shirts or banyans. Women: Saree, Set-Mundu, or Pavada. Salwar kameez, pants, and modern western dresses are strictly banned.',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 17. Shirdi (Shri Saibaba Sansthan Temple)
  {
    id: 'temple-shirdi',
    name: 'Shri Saibaba Sansthan Temple (Shirdi)',
    deity: 'Shri Sai Baba of Shirdi (Samadhi Mandir & Dwarkamai)',
    city: 'Shirdi',
    state: 'Maharashtra',
    address: 'Mauli Nagar, Shirdi, Rahata Taluka, Ahmednagar District, Maharashtra 423109',
    lat: 19.7668,
    lng: 74.4762,
    description: 'One of the world foremost spiritual sanctuaries where saint Shri Sai Baba lived, taught universal harmony, faith ("Shraddha") and patience ("Saburi"), and entered Mahasamadhi.',
    history: 'Sai Baba arrived in Shirdi in the mid-19th century, took abode at the dilapidated Dwarkamai mosque tending the eternal Dhuni fire, and took Mahasamadhi in October 1918. The holy complex encompasses the Samadhi Mandir featuring an Italian white marble murti of Baba, Gurusthan under the neem tree, Chavadi, and Lendi garden.',
    timings: {
      morning: '04:00 AM – 11:15 PM',
      evening: 'Continuous darshan throughout the day',
      notes: 'Kakad Aarti at 04:30 AM; Shej Aarti at 10:30 PM. Mega Prasadalaya operates serving over 50,000 consecrated meals daily.',
    },
    pujas: [
      { id: 'p-sb1', name: 'Kakad Aarti', timing: '04:30 AM', significance: 'Dawn awakening aarti with lamps and stotras', fee: '₹600' },
      { id: 'p-sb2', name: 'Madhyan Aarti', timing: '12:00 PM', significance: 'Midday grand arati with bell resonance', fee: '₹400' },
      { id: 'p-sb3', name: 'Dhoop Aarti', timing: '06:15 PM', significance: 'Sunset fragrant incense offering', fee: '₹400' },
      { id: 'p-sb4', name: 'Shej Aarti', timing: '10:30 PM', significance: 'Night closing lullaby arati', fee: '₹400' },
      { id: 'p-sb5', name: 'Abhishek Puja', timing: '07:00 AM – 11:00 AM', significance: 'Holy bath ritual conducted by devotee families with Sansthan purohits', fee: '₹250' },
    ],
    contact: {
      phone: '+91 2423 258500',
      email: 'saibaba@sai.org.in',
      website: 'https://sai.org.in',
    },
    photos: [
      '/images/temples/temple-shirdi.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-sb1',
        title: 'Shri Sai Baba Punyatithi Festival',
        date: '2026-10-20',
        time: 'All Day',
        description: 'Grand three-day Mahasamadhi commemoration attracting over 300,000 pilgrims on foot from across India.',
      },
      {
        id: 'ev-sb2',
        title: 'Guru Purnima Mahotsav',
        date: '2026-07-29',
        time: '05:00 AM',
        description: 'Solemn festival dedicated to honoring the Satguru with continuous Akhand Ramayan and Sai Satcharitra path.',
      },
    ],
    dressCode: 'Modest respectful clothing. Devotees are requested to maintain solemnity. Free mega Prasadalaya serves hot satvik meals continuously.',
    createdAt: '2024-01-16T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // 18. Somnath (Shree Somnath Jyotirlinga Temple)
  {
    id: 'temple-somnath',
    name: 'Shree Somnath Jyotirlinga Temple (Prabhas Patan)',
    deity: 'Lord Somnath (First among the 12 Jyotirlingas of Shiva)',
    city: 'Prabhas Patan',
    state: 'Gujarat',
    address: 'Somnath Mandir Marg, Prabhas Patan, Veraval, Gujarat 362268',
    lat: 20.8880,
    lng: 70.4013,
    description: 'The first of the twelve sacred Jyotirlinga shrines of Lord Shiva situated on the shore of the Arabian Sea, known as the Shrine Eternal.',
    history: 'Known as the Shrine Eternal. Built in the Chalukya style of temple architecture under Sardar Vallabhbhai Patel following Indian independence.',
    timings: {
      morning: '06:00 AM – 09:30 PM (Continuous Darshan)',
      evening: 'Aarti at 07:00 PM, Sound & Light Show 08:00 PM',
      notes: 'Temple remains open all day without midday closure.',
      specialDays: 'Maha Shivratri features all-night four-pahar Mahapuja.',
    },
    pujas: [
      { id: 'p-s1', name: 'Pratah Aarti', timing: '07:00 AM', significance: 'Morning aarti with Shankhanaad', fee: 'Free' },
      { id: 'p-s2', name: 'Madhyahna Aarti', timing: '12:00 PM', significance: 'Midday grand offering', fee: 'Free' },
      { id: 'p-s3', name: 'Sandhya Aarti', timing: '07:00 PM', significance: 'Evening oceanfront arati', fee: 'Free' },
      { id: 'p-s4', name: 'Laghu Rudra Abhishek', timing: '08:00 AM – 10:30 AM', significance: 'Vedic chanting with continuous holy waters', fee: '₹1,100' },
    ],
    contact: {
      phone: '+91 2876 231200',
      email: 'info@somnath.org',
      website: 'https://somnath.org',
    },
    photos: [
      '/images/temples/temple-somnath.jpg',
    ],
    status: 'representative_verified',
    adminId: 'user-admin-somnath',
    claimedBy: 'user-admin-somnath',
    claimStatus: 'claimed',
    contributors: [],
    events: [
      {
        id: 'ev-s1',
        title: 'Maha Shivaratri Mahotsav',
        date: '2026-03-08',
        time: 'All Night',
        description: 'Special continuous abhishekam, palanquin yatra, and laser illumination show.',
      },
    ],
    dressCode: 'Modest traditional dress. Leather belts, bags, electronic items, and cameras must be deposited at the locker room.',
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // Bonus sacred kshetras preserved for completeness
  {
    id: 'temple-kashi',
    name: 'Shri Kashi Vishwanath Temple (Varanasi)',
    deity: 'Lord Vishwanath (Shiva Jyotirlinga)',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    address: 'Lahori Tola, Varanasi, Uttar Pradesh 221001',
    lat: 25.3109,
    lng: 83.0107,
    description: 'One of the most sacred pilgrimage centers located along the western bank of the holy River Ganga in Kashi.',
    history: 'Rebuilt by Maharani Ahilyabai Holkar of Indore in 1780; modern Kashi Vishwanath Dham corridor connected to Ganga Ghats.',
    timings: {
      morning: '03:00 AM – 11:15 AM',
      evening: '12:20 PM – 11:00 PM',
      notes: 'Temple corridor open 24 hours for river views.',
    },
    pujas: [
      { id: 'p-k1', name: 'Mangala Aarti', timing: '03:00 AM', significance: 'First auspicious aarti of the day', fee: '₹350' },
      { id: 'p-k2', name: 'Bhog Aarti', timing: '11:15 AM', significance: 'Midday food offering', fee: '₹180' },
      { id: 'p-k3', name: 'Sapta Rishi Aarti', timing: '07:00 PM', significance: 'Conducted simultaneously by 7 venerable purohits', fee: '₹300' },
      { id: 'p-k4', name: 'Rudra Abhishek', timing: '06:00 AM – 01:00 PM', significance: 'Panchamrit ritual bathing with Vedic hymns', fee: '₹700' },
    ],
    contact: {
      phone: '+91 542 2392629',
      email: 'shrikashivishwanathvaranasi@gmail.com',
      website: 'https://shrikashivishwanath.org',
    },
    photos: [
      '/images/temples/temple-kashi.jpg',
    ],
    status: 'representative_verified',
    contributors: [],
    events: [
      {
        id: 'ev-k1',
        title: 'Dev Deepawali & Ganga Mahotsav',
        date: '2026-11-23',
        time: '05:00 PM',
        description: 'Lakhs of earthen lamps lit along all 84 ghats from Assi to Rajghat with Maha Aarti.',
      },
    ],
    dressCode: 'Traditional Indian attire. Prohibited items to be left in cloakroom.',
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'temple-brihadisvara',
    name: 'Brihadisvara Temple (Peruvudaiyar Kovil, Thanjavur)',
    deity: 'Lord Shiva (Brihadisvara)',
    city: 'Thanjavur',
    state: 'Tamil Nadu',
    address: 'Membalam Rd, Balaganapathy Nagar, Thanjavur, Tamil Nadu 613007',
    lat: 10.7828,
    lng: 79.1318,
    description: 'UNESCO World Heritage Site, quintessential example of Chola architecture built by Emperor Raja Raja Chola I.',
    history: 'Consecrated in 1010 CE; the vimana tower is 216 feet high and topped by an 80-tonne monolithic granite kumbam.',
    timings: {
      morning: '06:00 AM – 12:30 PM',
      evening: '04:00 PM – 08:30 PM',
    },
    pujas: [
      { id: 'p-b1', name: 'Usha Kalam', timing: '06:30 AM', significance: 'Early dawn puja', fee: 'Free' },
      { id: 'p-b2', name: 'Sayaratchai', timing: '06:00 PM', significance: 'Evening deeparadhana', fee: 'Free' },
      { id: 'p-b3', name: 'Maha Pradosham Abhishek', timing: '04:30 PM (Bi-monthly)', significance: 'Grand milk and sandal abhishekam to massive Nandi', fee: '₹100' },
    ],
    contact: {
      phone: '+91 4362 274476',
      email: 'thanjavurtourism@tn.gov.in',
    },
    photos: [
      '/images/temples/temple-brihadisvara.jpg',
    ],
    status: 'community_confirmed',
    contributors: [],
    events: [
      {
        id: 'ev-b1',
        title: 'Brahmotsavam & Raja Raja Chola Jayanthi',
        date: '2026-10-30',
        time: '09:00 AM',
        description: 'Sadhaya Vizha celebration celebrating Emperor Raja Raja Chola with classic Bharatanatyam recital.',
      },
    ],
    dressCode: 'Traditional Indian attire.',
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
];
